services:
  go_app:
    image: ghcr.io/dendanskemetode/legacyproject:latest
    expose:
      - "3000"
    environment:
      - PORT=3000
    networks:
      - backend
  nginx:
    build: ./network
    ports:
      - "80:80"
    depends_on:
      - go_app
    networks:
      - backend
  prometheus:
    image: prom/prometheus:latest
    volumes:
      - ./monetoring/prometheus.yml:/etc/prometheus/prometheus.yml
    ports:
      - "9090:9090"
    networks:
      - backend
  grafana:
    image: grafana/grafana:latest
    ports:
      - "3000:3000"
    environment:
      - GF_SECURITY_ADMIN_PASSWORD=admin
    depends_on:
      - prometheus
    networks:
      - backend

networks:
  backend:
    driver: bridge
