services:
  nginx:
    image: ghcr.io/dendanskemetode/legacyproject-nginx:latest
    ports:
      - "80:80"
    environment:
      - APP_HOST=${APP_HOST}
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "wget", "-qO-", "http://localhost:80/"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 10s
