name: Go Vet Linting

on:
  push:
    branches: ["**"] # kører på alle branches
  pull_request:
    branches: ["**"]

jobs:
  lint_go: # for go kode
    name: Lint with go vet
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v4 # downloader seneste version af go

      - name: Run go vet 
        run: cd app && go vet ./... # kører "go vet" som kun bliver succes hvis den ikke finder fejl

      - name: Run go tests
        run: cd app && go test ./...

  hadolint:
    name: Lint Dockerfiles
    needs: lint_go  # Wait for lint-go to finish
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Run Hadolint
        uses: hadolint/hadolint-action@v3.1.0
        with:
          dockerfile: "app/Dockerfile" # kun dockerfile i app-mappe
          failure-threshold: error